const API_URL = (import.meta.env.VITE_API_URL || 'https://api.piru.app/api').replace(/\/$/, '')
export type TipoEventoTracking = 'session_start' | 'product_view' | 'purchase'
export type EventoMetaPixel = 'ViewContent' | 'AddToCart' | 'InitiateCheckout' | 'Purchase'
type MetaFbq = ((...args: unknown[]) => void) & { queue?: unknown[]; loaded?: boolean; version?: string; callMethod?: (...args: unknown[]) => void }
type Contexto = { username: string; campaniaSlug?: string; campanaId?: number; recetaToken?: string; codigoPromocional?: string; actualizadoAt: number }
type Pendiente = { restauranteId: number; evento: Record<string, unknown>; intentos: number; reintentarAt: number }
const SESSION_MS = 30 * 60 * 1000, VISITOR = 'piru_marketing_visitor_v1', SESSION = 'piru_marketing_session_v1:', CONTEXT = 'piru_marketing_context_v1:', UNIQUE = 'piru_marketing_evento_unico_v1:', PIXEL_UNIQUE = 'piru_meta_pixel_unico_v1:', QUEUE = 'piru_marketing_queue_v1'
let flushing = false, gtm: string | null = null, pixel: string | null = null
declare global { interface Window { dataLayer?: Record<string, unknown>[]; fbq?: MetaFbq; _fbq?: MetaFbq } }
const safe = (s: Storage) => { try { s.getItem('__piru_tracking__'); return s } catch { return null } }
const local = () => typeof window === 'undefined' ? null : safe(window.localStorage)
const session = () => typeof window === 'undefined' ? null : safe(window.sessionStorage) ?? local()
const id = () => crypto?.randomUUID?.() ?? `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`
const usernameKey = (v: string) => v.trim().toLowerCase().slice(0, 255)
function read<T>(s: Storage | null, key: string): T | null { try { const v = s?.getItem(key); return v ? JSON.parse(v) : null } catch { return null } }
function write(s: Storage | null, key: string, value: unknown) { try { s?.setItem(key, JSON.stringify(value)) } catch { /* best-effort */ } }
function visitorId() { const s = local(), actual = s?.getItem(VISITOR); if (actual && actual.length <= 64) return actual; const next = id(); try { s?.setItem(VISITOR, next) } catch { /* private browsing */ }; return next }
export function obtenerSesionTracking(username: string) { const s = session(), key = SESSION + usernameKey(username), actual = read<{ sesionUuid: string; ultimaActividadAt: number }>(s, key), now = Date.now(); const value = actual && now - actual.ultimaActividadAt <= SESSION_MS ? actual : { sesionUuid: id(), ultimaActividadAt: now }; value.ultimaActividadAt = now; write(s, key, value); return value }
export function guardarContextoTracking(value: Omit<Contexto, 'actualizadoAt'>) { if (value.username) write(session(), CONTEXT + usernameKey(value.username), { ...value, username: usernameKey(value.username), actualizadoAt: Date.now() }) }
function contexto(username: string) { const value = read<Contexto>(session(), CONTEXT + usernameKey(username)); return value && Date.now() - value.actualizadoAt <= SESSION_MS ? value : null }
export function limpiarContextoTracking(username: string) { try { session()?.removeItem(CONTEXT + usernameKey(username)) } catch { /* best-effort */ } }
// El cupón del link se vuelve a validar en el servidor contra el total real del checkout.
export function codigoPromocionalMarketing(username: string) { return contexto(username)?.codigoPromocional?.trim().toUpperCase() || null }
export function contextoParaResolverMarketing(username: string) { return { visitorId: visitorId(), sesionUuid: obtenerSesionTracking(username).sesionUuid, eventoUuid: id() } }
export function contextoParaPedidoMarketing(username: string) { const value = contexto(username); return { visitorId: visitorId(), sesionUuid: obtenerSesionTracking(username).sesionUuid, ...(value?.campaniaSlug ? { campaniaSlug: value.campaniaSlug } : {}), ...(value?.campanaId ? { campanaId: value.campanaId } : {}), ...(value?.recetaToken ? { recetaToken: value.recetaToken } : {}) } }
export function configurarGtm(containerId: string | null | undefined) { const value = containerId?.trim().toUpperCase(); if (typeof window === 'undefined' || !value || !/^GTM-[A-Z0-9]{4,32}$/.test(value) || gtm === value) return; gtm = value; window.dataLayer ??= []; window.dataLayer.push({ 'gtm.start': Date.now(), event: 'gtm.js' }); if (document.querySelector(`script[data-piru-gtm="${value}"]`)) return; const script = document.createElement('script'); script.async = true; script.src = `https://www.googletagmanager.com/gtm.js?id=${encodeURIComponent(value)}`; script.dataset.piruGtm = value; document.head.appendChild(script) }
/* IDs que el index.html de este storefront ya inicializa: repetir el init duplicaría el PageView. */
const HTML_PIXELS = new Set<string>()
function metaItems(extras: Record<string, unknown>) { if (Array.isArray(extras.items)) return extras.items.flatMap((x: any) => x && (x.productoId ?? x.productId ?? x.id) != null ? [{ item_id: String(x.productoId ?? x.productId ?? x.id), item_name: x.nombreProducto ?? x.nombre, quantity: Number(x.cantidad) || 1 }] : []); return extras.productoId != null ? [{ item_id: String(extras.productoId), item_name: extras.nombreProducto as string, quantity: Number(extras.cantidad) || 1 }] : [] }
function metaParams(evento: EventoMetaPixel, extras: Record<string, unknown>) { const items = metaItems(extras), p: Record<string, unknown> = { currency: typeof extras.moneda === 'string' ? extras.moneda : 'ARS' }, valor = Number(extras.valor); if (Number.isFinite(valor)) p.value = valor; if (items.length) { p.content_ids = items.map(x => x.item_id); p.content_type = 'product'; p.num_items = items.reduce((t, x) => t + x.quantity, 0); const solo = items.length === 1 ? items[0].item_name : undefined; if (solo && (evento === 'ViewContent' || evento === 'AddToCart')) p.content_name = solo } return p }
function installFbq() { if (typeof window.fbq === 'function') return; const fbq = ((...args: unknown[]) => { if (fbq.callMethod) fbq.callMethod(...args); else fbq.queue!.push(args) }) as MetaFbq; fbq.queue = []; fbq.loaded = true; fbq.version = '2.0'; window.fbq = fbq; window._fbq = fbq; const script = document.createElement('script'); script.async = true; script.src = 'https://connect.facebook.net/en_US/fbevents.js'; script.dataset.piruMetaPixel = '1'; document.head.appendChild(script) }
export function configurarMetaPixel(pixelId: string | null | undefined) { const value = pixelId?.trim(); if (typeof window === 'undefined' || !value || !/^\d{15,16}$/.test(value) || pixel === value) return; pixel = value; if (HTML_PIXELS.has(value)) return; installFbq(); window.fbq!('init', value); window.fbq!('track', 'PageView') }
/* Misma semántica que el snippet de Meta: `callMethod` existe una vez cargado fbevents.js. */
export function registrarEventoPixel(evento: EventoMetaPixel, extras: Record<string, unknown> = {}) { if (typeof window === 'undefined' || typeof window.fbq !== 'function') return; try { window.fbq('track', evento, metaParams(evento, extras)) } catch { /* best-effort */ } }
export function registrarEventoPixelUnaVez(evento: EventoMetaPixel, clave: string, extras: Record<string, unknown> = {}) { const s = session(), key = `${PIXEL_UNIQUE}${pixel ?? 'sin-pixel'}:${evento}:${clave}`; if (s?.getItem(key)) return false; try { s?.setItem(key, '1') } catch { /* best-effort */ }; registrarEventoPixel(evento, extras); return true }
function dataLayer(tipo: TipoEventoTracking, extras: Record<string, unknown>) { if (!gtm || typeof window === 'undefined') return; if (tipo === 'session_start') { window.dataLayer?.push({ event: 'session_start' }); return }; const items = Array.isArray(extras.items) ? extras.items.map((x: any) => ({ item_id: String(x.productoId ?? x.id), item_name: x.nombreProducto ?? x.nombre, price: Number(x.precio ?? x.valor), quantity: x.cantidad })) : extras.productoId ? [{ item_id: String(extras.productoId), item_name: extras.nombreProducto, price: Number(extras.valor), quantity: Number(extras.cantidad) || 1 }] : undefined; const ecommerce: Record<string, unknown> = { currency: typeof extras.moneda === 'string' ? extras.moneda : 'ARS', ...(items ? { items } : {}), ...(Number.isFinite(Number(extras.valor)) ? { value: Number(extras.valor) } : {}) }; if (tipo === 'purchase') { if (extras.pedidoUnificadoId == null) return; ecommerce.transaction_id = String(extras.pedidoUnificadoId) }; window.dataLayer?.push({ ecommerce: null }); window.dataLayer?.push({ event: tipo === 'product_view' ? 'view_item' : tipo, ecommerce }) }
const queue = () => read<Pendiente[]>(local(), QUEUE) ?? []
const saveQueue = (value: Pendiente[]) => write(local(), QUEUE, value.slice(-100))
function sendNow(restauranteId: number, evento: Record<string, unknown>) { if (typeof window === 'undefined') return; const payload = JSON.stringify({ restauranteId, eventos: [evento] }), body = new Blob([payload], { type: 'text/plain;charset=UTF-8' }); try { if (typeof navigator.sendBeacon === 'function' && navigator.sendBeacon(`${API_URL}/public/marketing/events`, body)) return } catch { /* fetch fallback */ }; void fetch(`${API_URL}/public/marketing/events`, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=UTF-8' }, body: payload, keepalive: true }).catch(() => {}) }
export function registrarEventoTracking(restauranteId: number, username: string, tipo: TipoEventoTracking, extras: Record<string, unknown> = {}) { if (!Number.isInteger(restauranteId) || restauranteId <= 0) return; dataLayer(tipo, extras); const c = contexto(username), metadata = { ...(extras.metadata as Record<string, unknown> | undefined), ...(c?.campaniaSlug ? { campaniaSlug: c.campaniaSlug } : {}) }, touch = c?.campanaId ? { tipo: 'campana' as const, campanaId: c.campanaId } : undefined, evento = { eventoUuid: id(), sesionUuid: obtenerSesionTracking(username).sesionUuid, visitorId: visitorId(), tipo, ocurridoAt: new Date().toISOString(), ...extras, ...(touch ? { touch } : {}), ...(Object.keys(metadata).length ? { metadata } : {}) }; sendNow(restauranteId, evento) }
export function registrarEventoTrackingUnaVez(restauranteId: number, username: string, tipo: TipoEventoTracking, clave: string, extras: Record<string, unknown> = {}) { const s = session(), key = `${UNIQUE}${restauranteId}:${obtenerSesionTracking(username).sesionUuid}:${tipo}:${clave}`; if (s?.getItem(key)) return false; try { s?.setItem(key, '1') } catch { /* server idempotency remains */ }; registrarEventoTracking(restauranteId, username, tipo, extras); return true }
export async function enviarEventosPendientes() { if (flushing || typeof window === 'undefined' || !navigator.onLine) return; flushing = true; try { const now = Date.now(), original = queue(), first = original.find(x => x.reintentarAt <= now); if (!first) return; const batch = original.filter(x => x.restauranteId === first.restauranteId && x.reintentarAt <= now).slice(0, 20), ids = new Set(batch.map(x => x.evento.eventoUuid as string)); try { const response = await fetch(`${API_URL}/public/marketing/events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ restauranteId: first.restauranteId, eventos: batch.map(x => x.evento) }), keepalive: true }); if (!response.ok) throw new Error(); saveQueue(original.filter(x => !ids.has(x.evento.eventoUuid as string))) } catch { saveQueue(original.map(x => { if (!ids.has(x.evento.eventoUuid as string)) return x; const intentos = x.intentos + 1; return intentos >= 5 ? null : { ...x, intentos, reintentarAt: now + Math.min(60000, 1000 * 2 ** (intentos - 1)) } }).filter((x): x is Pendiente => x !== null)) } } finally { flushing = false } }
